![](https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Scikit_learn_logo_small.svg/1200px-Scikit_learn_logo_small.svg.png)

# scikit-learn을 이용하여 붓꽃(Iris) 품종 데이터 예측하기

In [97]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt


import sklearn # 이것만 한다고 해서 모두 import 되지 않음.
# from sklearn import * 로 해야됨
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [98]:
sklearn.__version__

'0.20.3'

## 데이터 불러오기

In [99]:
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

## 데이터 확인하기

In [100]:
# iris 데이터셋 확인
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [101]:
# iris 내 data 확인
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [102]:
# iris 내 target
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [103]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [104]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [105]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [106]:
iris.filename

'/anaconda3/lib/python3.6/site-packages/sklearn/datasets/data/iris.csv'

In [107]:
iris_data = iris.data

In [108]:
iris_label = iris.target

In [109]:
iris_df = pd.DataFrame(data=iris_data,columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
5                  5.4               3.9                1.7               0.4   
6                  4.6               3.4                1.4               0.3   
7                  5.0               3.4                1.5               0.2   
8                  4.4               2.9                1.4               0.2   
9                  4.9               3.1                1.5               0.1   
10                 5.4               3.7                1.5               0.2   
11                 4.8               3.4                1.6               0.2   
12                 4.8               3.0                1.4               0.1   
13                 4.3               3.0                1.1               0.1   
14                 5.8               4.0                1.2               0.2   
15                 5.7               4.4                1.5               0.4   
16                 5.4               3.9                1.3               0.4   
17                 5.1               3.5                1.4               0.3   
18                 5.7               3.8                1.7               0.3   
19                 5.1               3.8                1.5               0.3   
20                 5.4               3.4                1.7               0.2   
21                 5.1               3.7                1.5               0.4   
22                 4.6               3.6                1.0               0.2   
23                 5.1               3.3                1.7               0.5   
24                 4.8               3.4                1.9               0.2   
25                 5.0               3.0                1.6               0.2   
26                 5.0               3.4                1.6               0.4   
27                 5.2               3.5                1.5               0.2   
28                 5.2               3.4                1.4               0.2   
29                 4.7               3.2                1.6               0.2   
..                 ...               ...                ...               ...   
120                6.9               3.2                5.7               2.3   
121                5.6               2.8                4.9               2.0   
122                7.7               2.8                6.7               2.0   
123                6.3               2.7                4.9               1.8   
124                6.7               3.3                5.7               2.1   
125                7.2               3.2                6.0               1.8   
126                6.2               2.8                4.8               1.8   
127                6.1               3.0                4.9               1.8   
128                6.4               2.8                5.6               2.1   
129                7.2               3.0                5.8               1.6   
130                7.4               2.8                6.1               1.9   
131                7.9               3.8                6.4               2.0   
132                6.4               2.8                5.6               2.2   
133                6.3               2.8                5.1               1.5   
134                6.1               2.6                5.6               1.4   
135                7.7               3.0                6.1               2.3   
136                6.3               3.4                5.6               2.4   
137                6.4              

In [110]:
len(iris_df)

150

## 데이터 학습 및 평가하기

### 결정트리 분류 객체 생성

In [129]:
dt_clf = DecisionTreeClassifier()

### 학습

In [130]:
dt_clf.fit(iris.data, iris.target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

### 평가

In [131]:
dt_clf.score(iris.data, iris.target)

1.0

## Train/Test 데이터 나누어 학습하기

In [132]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target,
                                                    test_size = 0.3,
                                                    random_state = 100)

In [133]:
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [134]:
dt_clf.score(X_train, y_train)

1.0

In [135]:
dt_clf.score(X_test, y_test)

0.9555555555555556

In [136]:
# 실제 결과
y_test

array([2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 1, 1, 1, 2, 2, 2, 0,
       2, 0, 1, 2, 1, 0, 1, 2, 1, 1, 2, 0, 0, 1, 0, 1, 2, 2, 0, 1, 2, 2,
       0])

In [137]:
# 예측한 결과
y_pred = dt_clf.predict(X_test)
y_pred

array([2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 1, 1, 2, 2, 2, 2, 0,
       2, 0, 1, 2, 1, 0, 1, 2, 1, 1, 1, 0, 0, 1, 0, 1, 2, 2, 0, 1, 2, 2,
       0])

In [138]:
accuracy_score(y_test,y_pred) # dt_clf.score(X_test, y_test)랑 같은 거

0.9555555555555556

In [142]:
dt_clf.predict_proba(X_test)

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]])

## 교차 검증 (Cross Validation)

### K Fold
![](../img/big-data_kfold.png)

In [121]:
from sklearn.model_selection import KFold

In [122]:
kfold = KFold(n_splits = 5, shuffle=False)

In [123]:
acc_list = list()
for train_idx, test_idx in kfold.split(iris.data,iris.target):
    X_train, X_test = iris.data[train_idx], iris.data[test_idx]
    y_train, y_test = iris.target[train_idx], iris.target[test_idx]
    dt_clf.fit(X_train,y_train)
    acc_list.append(dt_clf.score(X_test, y_test))
acc_list

[1.0, 1.0, 0.8333333333333334, 0.9333333333333333, 0.7333333333333333]

In [124]:
np.array(acc_list).mean()

0.9

### Stratified K Fold

In [125]:
from sklearn.model_selection import StratifiedKFold

In [126]:
skfold = StratifiedKFold(n_splits = 5, shuffle=False)

In [127]:
acc_list = list()
for train_idx, test_idx in skfold.split(iris.data,iris.target):
    X_train, X_test = iris.data[train_idx], iris.data[test_idx]
    y_train, y_test = iris.target[train_idx], iris.target[test_idx]
    dt_clf.fit(X_train,y_train)
    acc_list.append(dt_clf.score(X_test, y_test))
acc_list

[0.9666666666666667, 0.9666666666666667, 0.9, 0.9666666666666667, 1.0]

In [128]:
np.array(acc_list).mean()

0.9600000000000002

### 교차검증을 보다 간단하게 하는 방법

In [144]:
from sklearn.model_selection import cross_val_score, cross_validate

In [147]:
cross_val_predict(dt_clf,
                  iris.data,
                  iris.target,
                  cv = 5 # 나눌 덩어리 횟수
                 )

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [149]:
pd.DataFrame(cross_validate(dt_clf,
                            iris.data,
                            iris.target,
                            cv=5,
                            return_train_score=True))

fit_time  score_time  test_score  train_score
0  0.001191    0.000620    0.966667          1.0
1  0.000833    0.000387    0.966667          1.0
2  0.000520    0.000257    0.900000          1.0
3  0.000343    0.000221    1.000000          1.0
4  0.000338    0.000216    1.000000          1.0

In [150]:
pd.DataFrame(cross_validate(dt_clf,
                            X_train,
                            y_train,
                            cv=5,
                            return_train_score=True))

fit_time  score_time  test_score  train_score
0  0.001046    0.000325    0.954545          1.0
1  0.000466    0.000464    0.909091          1.0
2  0.000368    0.000248    0.952381          1.0
3  0.000331    0.000219    1.000000          1.0
4  0.000341    0.000878    1.000000          1.0

In [152]:
dt_clf.predict(X_test)

array([2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 1, 1, 2, 2, 2, 2, 0,
       2, 0, 1, 2, 1, 0, 1, 2, 1, 1, 1, 0, 0, 1, 0, 1, 2, 2, 0, 1, 2, 2,
       0])

In [153]:
dt_clf.score(X_test,y_test)

0.9555555555555556

### Grid Search Cross Validation 로 하이퍼파라미터 최적화(튜닝)

In [154]:
from sklearn.model_selection import GridSearchCV

In [155]:
# 테스트해보고자 하는 파라미터 값들을 정의
# 사전 타입으로 정의
# 총 조합 12가지 ( 3x2x2 )
params = {
    'max_depth' : [3,5,7],
    'min_samples_split': [3,5],
    'splitter' : ['best','random']
}

In [172]:
grid_dt = GridSearchCV(dt_clf,  # estimator 객체
                       param_grid=params,
                       cv=5,
                       n_jobs=-1 # 병렬처리
                      )

In [173]:
# 총 60배로 학습을 더 많이 함
# 12가지 조합으로 cv=5번씩이니까
grid_dt.fit(X_train,y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid={'max_depth': [3, 5, 7], 'min_samples_split': [3, 5], 'splitter': ['best', 'random']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [174]:
grid_dt.best_estimator_

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=3,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [175]:
grid_dt.best_params_

{'max_depth': 3, 'min_samples_split': 3, 'splitter': 'best'}

In [176]:
# 가장 좋은 트리 모델 찾아서
grid_dt.best_estimator_.score(X_test,y_test)

0.9555555555555556

In [178]:
# 전체적인 결과 출력
pd.DataFrame(grid_dt.cv_results_)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.001049      0.000097         0.000464        0.000011   
1        0.001117      0.000750         0.000402        0.000099   
2        0.000510      0.000155         0.000330        0.000033   
3        0.000409      0.000013         0.000336        0.000048   
4        0.000397      0.000046         0.000271        0.000046   
5        0.000393      0.000065         0.000231        0.000040   
6        0.000554      0.000110         0.000252        0.000079   
7        0.000410      0.000090         0.000223        0.000047   
8        0.000421      0.000065         0.000246        0.000064   
9        0.000324      0.000096         0.000236        0.000042   
10       0.000377      0.000090         0.000244        0.000034   
11       0.000247      0.000031         0.000187        0.000025   

   param_max_depth param_min_samples_split param_splitter  \
0                3                       3           best   
1                3                       3         random   
2                3                       5           best   
3                3                       5         random   
4                5                       3           best   
5                5                       3         random   
6                5                       5           best   
7                5                       5         random   
8                7                       3           best   
9                7                       3         random   
10               7                       5           best   
11               7                       5         random   

                                               params  split0_test_score  \
0   {'max_depth': 3, 'min_samples_split': 3, 'spli...           0.954545   
1   {'max_depth': 3, 'min_samples_split': 3, 'spli...           0.909091   
2   {'max_depth': 3, 'min_samples_split': 5, 'spli...           0.954545   
3   {'max_depth': 3, 'min_samples_split': 5, 'spli...           0.909091   
4   {'max_depth': 5, 'min_samples_split': 3, 'spli...           0.954545   
5   {'max_depth': 5, 'min_samples_split': 3, 'spli...           0.954545   
6   {'max_depth': 5, 'min_samples_split': 5, 'spli...           0.954545   
7   {'max_depth': 5, 'min_samples_split': 5, 'spli...           0.954545   
8   {'max_depth': 7, 'min_samples_split': 3, 'spli...           0.954545   
9   {'max_depth': 7, 'min_samples_split': 3, 'spli...           0.954545   
10  {'max_depth': 7, 'min_samples_split': 5, 'spli...           0.954545   
11  {'max_depth': 7, 'min_samples_split': 5, 'spli...           0.954545   

    split1_test_score  ...  mean_test_score  std_test_score  rank_test_score  \
0            0.954545  ...         0.980952        0.022427                1   
1            0.772727  ...         0.866667        0.051740               12   
2            0.954545  ...         0.980952        0.022427                1   
3            0.909091  ...         0.942857        0.044855                9   
4            0.954545  ...         0.980952        0.022427                1   
5            0.954545  ...         0.971429        0.022427                4   
6            0.909091  ...         0.971429        0.036718                4   
7            0.863636  ...         0.933333        0.062978               10   
8            0.909091  ...         0.971429        0.036718                4   
9            0.863636  ...         0.952381        0.050149                8   
10           0.909091  ...         0.971429        0.036718                4   
11           0.818182  ...         0.914286        0.067788               11   

    split0_train_score  split1_train_score  split2_train_score  \
0             0.987952            0.987952            0.976190   
1             0.879518            0.819277            0.916667   
2             0.987952            0.987952            0.976190   
3             0.963855         